create extension if not exists pgcrypto with schema extensions;

create table if not exists public.tbl_department (
  department_id bigint generated by default as identity primary key,
  department_name text not null
);

create table if not exists public.tbl_year (
  year_id bigint generated by default as identity primary key,
  year_name text not null
);

create table if not exists public.tbl_designation (
  designation_id bigint generated by default as identity primary key,
  designation_name text not null
);

create table if not exists public.tbl_programme (
  programme_id bigint generated by default as identity primary key,
  programme_name text not null,
  department_id bigint references public.tbl_department(department_id) on update cascade on delete set null
);

create table if not exists public.tbl_admin (
  admin_id uuid primary key references auth.users(id) on update cascade on delete cascade,
  admin_name text not null,
  admin_email text unique,
  admin_password text,
  admin_photo text
);

create table if not exists public.tbl_student (
  student_id bigint primary key,
  student_name text not null,
  stud_email text unique,
  stud_contact text,
  stud_password text,
  class_id bigint,
  stud_gender text,
  stud_photo text,
  year_id bigint references public.tbl_year(year_id) on update cascade on delete set null,
  department_id bigint references public.tbl_department(department_id) on update cascade on delete set null,
  programme_id bigint references public.tbl_programme(programme_id) on update cascade on delete set null
);

create table if not exists public.tbl_tutor (
  tutor_id bigint primary key,
  tutor_name text not null,
  tutor_email text unique,
  tutor_photo text,
  tutor_password text,
  tutor_contact text,
  department_id bigint references public.tbl_department(department_id) on update cascade on delete set null,
  designation_id bigint references public.tbl_designation(designation_id) on update cascade on delete set null,
  programme_id bigint references public.tbl_programme(programme_id) on update cascade on delete set null,
  year_id bigint references public.tbl_year(year_id) on update cascade on delete set null
);

create table if not exists public.tbl_attendance (
  attendance_id uuid primary key default gen_random_uuid(),
  attendance_date date not null default current_date,
  student_id bigint references public.tbl_student(student_id) on update cascade on delete cascade,
  entry_time time,
  exit_time time,
  period text,
  status text,
  first_period text,
  second_period text,
  third_period text,
  fourth_period text,
  fifth_period text,
  created_at timestamptz not null default now()
);

create table if not exists public.tbl_complaints (
  id bigint generated by default as identity primary key,
  complaint_text text not null,
  student_id bigint references public.tbl_student(student_id) on update cascade on delete cascade,
  status text not null default 'pending',
  created_at date not null default current_date
);

create index if not exists tbl_admin_email_idx on public.tbl_admin(admin_email);
create index if not exists tbl_student_email_idx on public.tbl_student(stud_email);
create index if not exists tbl_student_filters_idx on public.tbl_student(department_id, programme_id, year_id);
create index if not exists tbl_tutor_email_idx on public.tbl_tutor(tutor_email);
create index if not exists tbl_tutor_filters_idx on public.tbl_tutor(department_id, programme_id, year_id);
create index if not exists tbl_attendance_student_date_idx on public.tbl_attendance(student_id, attendance_date);
create index if not exists tbl_complaints_student_idx on public.tbl_complaints(student_id);

alter table public.tbl_department enable row level security;
alter table public.tbl_year enable row level security;
alter table public.tbl_designation enable row level security;
alter table public.tbl_programme enable row level security;
alter table public.tbl_admin enable row level security;
alter table public.tbl_student enable row level security;
alter table public.tbl_tutor enable row level security;
alter table public.tbl_attendance enable row level security;
alter table public.tbl_complaints enable row level security;

drop policy if exists "department read/write" on public.tbl_department;
drop policy if exists "year read/write" on public.tbl_year;
drop policy if exists "designation read/write" on public.tbl_designation;
drop policy if exists "programme read/write" on public.tbl_programme;
drop policy if exists "admin read/write" on public.tbl_admin;
drop policy if exists "student read/write" on public.tbl_student;
drop policy if exists "tutor read/write" on public.tbl_tutor;
drop policy if exists "attendance read/write" on public.tbl_attendance;
drop policy if exists "complaints read/write" on public.tbl_complaints;

create policy "department read/write" on public.tbl_department for all using (true) with check (true);
create policy "year read/write" on public.tbl_year for all using (true) with check (true);
create policy "designation read/write" on public.tbl_designation for all using (true) with check (true);
create policy "programme read/write" on public.tbl_programme for all using (true) with check (true);
create policy "admin read/write" on public.tbl_admin for all using (true) with check (true);
create policy "student read/write" on public.tbl_student for all using (true) with check (true);
create policy "tutor read/write" on public.tbl_tutor for all using (true) with check (true);
create policy "attendance read/write" on public.tbl_attendance for all using (true) with check (true);
create policy "complaints read/write" on public.tbl_complaints for all using (true) with check (true);

insert into storage.buckets (id, name, public)
values
  ('admin', 'admin', true),
  ('attendance', 'attendance', true),
  ('tutor', 'tutor', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

drop policy if exists "admin bucket public read" on storage.objects;
drop policy if exists "admin bucket authenticated write" on storage.objects;
drop policy if exists "attendance bucket public read" on storage.objects;
drop policy if exists "attendance bucket authenticated write" on storage.objects;
drop policy if exists "tutor bucket public read" on storage.objects;
drop policy if exists "tutor bucket authenticated write" on storage.objects;

create policy "admin bucket public read" on storage.objects
  for select using (bucket_id = 'admin');

create policy "admin bucket authenticated write" on storage.objects
  for all to authenticated
  using (bucket_id = 'admin')
  with check (bucket_id = 'admin');

create policy "attendance bucket public read" on storage.objects
  for select using (bucket_id = 'attendance');

create policy "attendance bucket authenticated write" on storage.objects
  for all to authenticated
  using (bucket_id = 'attendance')
  with check (bucket_id = 'attendance');

create policy "tutor bucket public read" on storage.objects
  for select using (bucket_id = 'tutor');

create policy "tutor bucket authenticated write" on storage.objects
  for all to authenticated
  using (bucket_id = 'tutor')
  with check (bucket_id = 'tutor');

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;
